# Generated by Django 2.2.7 on 2020-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='update_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
